import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-6xl mx-auto px-4 py-8">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            About GridMix
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            Powering Transparency in the UK Energy Transition
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Main Description */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardContent className="p-8">
            <div className="prose prose-lg dark:prose-invert max-w-none">
              <p className="text-lg text-gray-700 dark:text-gray-300 leading-relaxed mb-6">
                GridMix is your live window into the UK's evolving electricity system. Built to track the real-time and historical performance of the national grid, GridMix offers a clear view of how power is generated, consumed, and decarbonized.
              </p>
              
              <p className="text-lg text-gray-700 dark:text-gray-300 leading-relaxed mb-6">
                From offshore wind in Scotland to solar farms across England, we break down how each energy source contributes to the grid — by the hour, week, and season. Whether you're a policymaker, researcher, or curious citizen, GridMix helps you follow the UK's journey to net-zero by 2050 with clarity and confidence.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Data Sources */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Where the Data Comes From — and Why It Matters
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              GridMix uses official datasets from Elexon's BMRS API, the UK's central platform for real-time electricity market information. We process and visualize this data to show:
            </p>
            
            <ul className="space-y-3 text-gray-700 dark:text-gray-300">
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                How much electricity is generated by each source (wind, gas, nuclear, etc.)
              </li>
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                When and where energy production shifts
              </li>
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                Trends over days, weeks, months, and years
              </li>
            </ul>
          </CardContent>
        </Card>

        {/* Technical Notes & Data Sources */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Technical Notes & Data Sources
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <div className="grid md:grid-cols-2 gap-6">
              {/* Primary Data Sources */}
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Primary Data Sources</h3>
                <div className="space-y-4">
                  <div className="border border-gray-200 dark:border-gray-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-gray-900 dark:text-white">Elexon BMRS API</h4>
                      <Badge variant="default">Primary</Badge>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                      Official UK electricity market data including generation, demand, and system balancing information
                    </p>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Updates:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">Every 5 minutes</div>
                      </div>
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Coverage:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">GB electricity system</div>
                      </div>
                    </div>
                  </div>

                  <div className="border border-gray-200 dark:border-gray-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-gray-900 dark:text-white">Carbon Intensity API</h4>
                      <Badge variant="secondary">Fallback</Badge>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                      National Grid ESO carbon intensity and generation mix data
                    </p>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Updates:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">Every 30 minutes</div>
                      </div>
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Coverage:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">GB grid carbon intensity</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Technical Implementation */}
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Technical Implementation</h3>
                <div className="space-y-3 text-sm text-gray-600 dark:text-gray-400">
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Data Processing:</strong> Real-time data fetching with fallback mechanisms and validation
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Update Frequency:</strong> Dashboard refreshes every 5 minutes during active hours
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Historical Data:</strong> 24-hour rolling window with hourly aggregation
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Data Quality:</strong> Automated validation and error handling for API failures
                  </div>
                </div>

                <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                  <h4 className="font-medium text-blue-900 dark:text-blue-100 mb-2">Data Accuracy</h4>
                  <p className="text-sm text-blue-800 dark:text-blue-200">
                    All data displayed comes directly from official UK energy system operators. 
                    GridMix does not modify or estimate values - we present the authentic data as provided by Elexon and National Grid ESO.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}