import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-6xl mx-auto px-4 py-8">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
            About GridMix
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            Powering Transparency in the UK Energy Transition
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        {/* Main Description */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardContent className="p-6">
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
              GridMix is your live window into the UK's evolving electricity system. Built to track the real-time and historical performance of the national grid, GridMix offers a clear, dynamic view of how electricity is generated, consumed, and decarbonised.
            </p>
            
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
              From giant wind farms off the Scottish coast to solar panels soaking up sun in the south, GridMix breaks down how each energy source keeps the lights on — every hour, every season. Whether you're diving deep into policy, exploring for research, backing clean tech, or just want to understand where your power comes from, GridMix helps you follow the UK's net zero journey with ease.
            </p>
          </CardContent>
        </Card>

        {/* Projects Across the UK */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Projects Across the UK
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
              The Projects page features an interactive map of renewable energy developments across the UK. Sourced from the official Renewable Energy Planning Database (REPD), it shows you where solar, wind, and battery storage projects are located, their operational status, and live output when available.
            </p>
          </CardContent>
        </Card>

        {/* Carbon Intensity Forecasts */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Carbon Intensity Forecasts
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
              Visit the Forecast page to view projected carbon intensity levels across the UK. These forecasts help you anticipate when the grid will be cleanest — so you can time your usage, plan grid-friendly activities, or simply stay informed.
            </p>
          </CardContent>
        </Card>

        {/* Data Sources */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Where the Data Comes From — and Why It Matters
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
              GridMix is powered by official, transparent datasets. Our core live data is sourced from Elexon's Balancing Mechanism Reporting Service (BMRS) — the UK's central platform for real-time electricity market information.
            </p>
            
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
              We process and visualise this data to show:
            </p>
            
            <ul className="space-y-3 text-sm text-gray-600 dark:text-gray-400">
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                How much electricity is generated by each source (wind, gas, nuclear, etc.)
              </li>
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                When and where production patterns shift
              </li>
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                Carbon intensity trends by region and time
              </li>
              <li className="flex items-start">
                <span className="w-2 h-2 bg-blue-500 rounded-full mt-2 mr-3 flex-shrink-0"></span>
                Long-term movements in the UK energy mix
              </li>
            </ul>
          </CardContent>
        </Card>

        {/* Technical Notes & Data Sources */}
        <Card className="border-gray-200 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-gray-900 dark:text-white">
              Technical Notes & Data Sources
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <div className="grid md:grid-cols-2 gap-6">
              {/* Primary Data Sources */}
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Primary Data Sources</h3>
                <div className="space-y-4">
                  <div className="border border-gray-200 dark:border-gray-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-gray-900 dark:text-white">Elexon BMRS API</h4>
                      <Badge variant="default">Primary</Badge>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                      Official UK electricity market data including generation, demand, and system balancing information
                    </p>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Updates:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">Every 5 minutes</div>
                      </div>
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Coverage:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">GB electricity system</div>
                      </div>
                    </div>
                  </div>

                  <div className="border border-gray-200 dark:border-gray-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-gray-900 dark:text-white">Carbon Intensity API</h4>
                      <Badge variant="secondary">Fallback</Badge>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                      National Grid ESO carbon intensity and generation mix data
                    </p>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Updates:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">Every 30 minutes</div>
                      </div>
                      <div>
                        <div className="text-gray-500 dark:text-gray-400">Coverage:</div>
                        <div className="text-gray-700 dark:text-gray-300 font-medium">GB grid carbon intensity</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Technical Implementation */}
              <div>
                <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Technical Implementation</h3>
                <div className="space-y-3 text-sm text-gray-600 dark:text-gray-400">
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Data Processing:</strong> Real-time data fetching with fallback mechanisms and validation
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Update Frequency:</strong> Dashboard refreshes every 5 minutes during active hours
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Historical Data:</strong> 24-hour rolling window with hourly aggregation
                  </div>
                  <div>
                    <strong className="text-gray-800 dark:text-gray-200">Data Quality:</strong> Automated validation and error handling for API failures
                  </div>
                </div>

                <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                  <h4 className="font-medium text-blue-900 dark:text-blue-100 mb-2">Data Accuracy</h4>
                  <p className="text-sm text-blue-800 dark:text-blue-200">
                    All data displayed comes directly from official UK energy system operators. 
                    GridMix does not modify or estimate values - we present the authentic data as provided by Elexon and National Grid ESO.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}